# You can use this file to create a new environment with all the packages by running:
# conda env create -f environment.yml

name: condor_env
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.10
  - tensorflow-gpu=2.11.0 #Need to change this to 'tensorflow=2.11.0' if you don't have a GPU 
  - keras=2.11.0
  - numpy=1.24.2
  - pandas=1.5.2
  - matplotlib=3.7.1  
  - seaborn=0.12.2
  - scikit-learn=1.1.1
  - jupyterlab=3.5.0
  - lxml=4.9.2
  - pandas-datareader=0.10.0
  - html5lib=1.1
  - requests=2.28.2
  - scrapy=2.8.0
  - bokeh=3.1.0
  - dash=2.9.1
  - gensim=4.3.1
  - nltk=3.7 
  - spacy=3.5.1
  - gensim=4.3.1
  - textblob=0.15.3
  - statsmodels=0.13.5
  - typing_extensions=4.5.0
  - yfinance=0.2.12 
  - tqdm=4.65.0
  - scipy=1.10.0
  - ipykernel=6.21.3 
  - beautifulsoup4=4.11.1
  - regex=2023.3.23
  - xgboost=1.7.4
  - black=23.1.0
  - yaml=0.2.5
  - mysql-connector-python=8.0.31
  - cryptography=39.0.2
  - pymysql=1.0.2
  - keyring=23.4.0 
  - secretstorage=3.3.1

  


